/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  safelist: [
    'bg-[#0f0f23]',
    'bg-[#1a1a2e]',
    'bg-white/5',
    'bg-white/10',
    'bg-white/20',
    'border-white/5',
    'border-white/10',
    'border-white/20',
    'border-blue-500/50',
    'border-blue-500/30',
    'border-green-500/30',
    'bg-black/60',
    'bg-black/20',
    'bg-black/80',
    'from-blue-950/60',
    'to-blue-900/60',
    'from-blue-950/40',
    'to-blue-950/40',
    'shadow-blue-500/50',
    'shadow-blue-500/20',
    'via-blue-800/10',
    'from-blue-900/10',
    'to-blue-900/10',
    'hover:border-blue-500/50',
    'hover:shadow-blue-500/20',
    'from-blue-600',
    'to-blue-800',
  ],
  plugins: [],
}
